### PR TITLE
Update `eslint-plugin-unicorn` to v40

### PR DESCRIPTION
**Pull request by fisker**
I just ran `generate:rules`, is this correct way?

### CODE REVIEW

**Comment by Shinigami92** [comment]
Theoretically yes, but after the generation I manually go through each file and check it.
Also I only comment those which are relevant, in this case please only commit the unicorn stuff and ignore the other rules.

**Comment by Shinigami92** [comment]
Looks like you already did that, will review and double check it later when I have more time :slightly_smiling_face:

**Comment by Shinigami92** [comment]
Hope I will find time in the next two evenings, sry for that delay

**Comment by fisker** [comment]
I don't really use this package, I'm just trying to help. No  rush.

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
