### PR TITLE
refactor: support node16+ module resolution

### PR DESCRIPTION
**Pull request by sxzz**
Support `"moduleResolution": "NodeNext"`

### CODE REVIEW

**Review by Shinigami92 — CHANGES_REQUESTED** [review]
Sorry but no.
I personally don't like TypeScripts decision to have .js imports in NodeNext.

There must be another way, and it also worked the last years without such quirks.
I do like `moduleResolution: bundler`, maybe that could help us and we need to compile our files to handle this and output something.

---

I will also not allow setting `"skipLibCheck": true`, because this is a really bad option and we wont get errors at compile time anymore if something changed in the dependencies (even dev deps in scripts or something like that)

**Comment by sxzz** [comment]
The problem we have now is that it blocks downstream using `moduleResolution: node16`. 
 See https://arethetypeswrong.github.io/?p=eslint-define-config%401.23.0

And there are two ways to solve it:
- Use bundler, like tsup (maybe not, I didn't try)
- Or this PR

**Comment by Shinigami92** [comment]
Could you try a separate PR with tsup + mode:bundler 

I'm just not sure with tsup and handling .d.ts files
But if we can omit .js imports in anyway, it is a better solution

**Comment by Shinigami92** [comment]
@sxzz just to give you some "prio"-info
I will try to find some dedicated time for working on this repo the upcoming weekend

so maybe await upcoming weekend before running in to many merge conflicts 😉

**Pull request closed without merging**
