### PR TITLE
feat: improve type suggestions with specific defineFlatConfig

### PR DESCRIPTION
**Pull request by sxzz**
- Add unit test.
  - Types will be checked by `tsc`.
- fix returning value of `defineConfig`.

### CODE REVIEW

**Comment by sxzz** [comment]
@Shinigami92 It's really hard to combine all kinds of configs into one function.

`ignores` is one of the keys of the flat config, but `env` is not. However, there's still a hint of `env`. 
image

If I add `env`, the config will change to the normal config again.
image

---

It can really easily lead to a mix of the normal config and flat config. I have no idea, what do you think? @Shinigami92

**Comment by Shinigami92** [comment]
Try to combine all into one function:

```ts
export function defineConfig<
  Config extends ESLintConfig | FlatESLintConfig | FlatESLintConfigs // maybe with "= ESLintConfig" for default
>(config: Config): Config;
```

**Comment by sxzz** [comment]
@Shinigami92 I tried, but it's still like I said (https://github.com/Shinigami92/eslint-define-config/pull/150#issuecomment-1295931656). All keys of config are optional, so TypeScript is unable to figure out which kind of config.

**Comment by Shinigami92** [comment]
Yeah, but it has two benefits
1. the user can specify via generic argument explicitly what they want (like `const conf = defineConfig<FlatESLintConfig>({})`
2. if the values of the keys are of equal type, then it doesn't matter if it's flat or non flat config

An eslint config doesn't change that often. The benefit is more like having autosuggestion for rules and see deprecated rules

**Comment by sxzz** [comment]
- But we cannot use type generic in js files.
- The values of flat config are not the same as `config` (except `rules`). The point is if users are not familiar with ESLint config, the hint will provide all keys of both flat config and non-flat config. It's very easy to have a mixed config with flat and non-flat config. `.eslintrc` is the non-flat config file, `eslint.config.js` is the flat config file. And then some keys will be ignored and some values could be wrong.

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
Yeah... okay, now I understand better what you initially mean

So I think we have no better option as defining a special `defineFlatConfig` so it is separated from the default eslint non flat config
Because of using LiteralUnion which results in a string, `defineFlatConfig`'s option is poluted with functions like `at()` and such weird stuff :shrug: 
But not sure what we can do about that

**Comment by sxzz** [comment]
I think maybe we could remove `LiteralUnion` of `PredefinedConfig`, since it's a built-in config from eslint. I think it will be not changed frequently.

**Comment by Shinigami92** [comment]
> I think maybe we could remove `LiteralUnion` of `PredefinedConfig`, since it's a built-in config from eslint. I think it will be not changed frequently.

Yes, we could do that, but doesn't it allow all kind of presets? Like `plugin:@typescript-eslint/recommended`

**Comment by sxzz** [comment]
@Shinigami92 No, flat config requires import plugins explicitly.

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
