### PR TITLE
Patch rule files automatically

### PR DESCRIPTION
**Pull request by Shinigami92**
Running `pnpm run generate:rules` results in some files that are invalid
We can run `git diff -R src/rules/<plugin>/<rule>.d.ts > scripts/generate-rule-files/diffs/rules/<plugin>/<rule>.d.ts.diff` to generate a diff file that reverts what is invalid

### CODE REVIEW

**Comment by Shinigami92** [comment]
@Dimava and @Julien-R44 please review this PR and give me some feedback
When this is merged, we can go back to #177 🙂

**Comment by Julien-R44** [comment]
LGTM ! Much simpler than my over-engineered system with ASTs ahah 🤪

Do we agree that we can now close #142 ?

**Review by Julien-R44 — APPROVED** [review]

**Comment by Dimava** [comment]
@Shinigami92 LGTM

What happens if diff is not appliable?

BTW, would adding EventEmitter be a good idea for streamlining logging, counting and #137 ?

**Comment by Dimava** [comment]
@Shinigami92 please add fixes for #181

**Comment by Shinigami92** [comment]
> @Shinigami92 please add fixes for #181

Will do in separate PR 👍

**Comment by Shinigami92** [comment]
> What happens if diff is not appliable?

I have not checked that, but I assume it would fail or something like that
Theoretically it is the same mechanism as https://www.npmjs.com/package/patch-package is doing

> BTW, would adding EventEmitter be a good idea for streamlining logging, counting and #137 ?

Could you explain a bit more? Maybe outsource this discussion into a new separate issue/discussion

**Pull request merged**
